using System;
using System.Collections.Generic;
using System.Linq;
using Dalamud.Game.Inventory;
using ECommons;
using ECommons.DalamudServices;
using ECommons.Logging;
using FFXIVClientStructs.FFXIV.Client.Game;
using Lumina.Excel.Sheets;
using TheCollector.CollectibleManager;

namespace TheCollector.Utility;

public static class ItemHelper
{
    public static List<GameInventoryItem> GetCurrentInventoryItems()
    {
        var inventoriesToFetch = new GameInventoryType[]
        {
            GameInventoryType.Inventory1, GameInventoryType.Inventory2, GameInventoryType.Inventory3,
            GameInventoryType.Inventory4
        };
        var inventoryItems = new List<GameInventoryItem>();
        for (int i = 0; i < inventoriesToFetch.Length; i++)
        {
            inventoryItems.AddRange(Svc.GameInventory.GetInventoryItems(inventoriesToFetch[i]));
        }
        return inventoryItems;
    }
    public static List<Item> GetLuminaItemsFromInventory()
    {
        List<Item>? luminaItems = new List<Item>();
        var inventoryItems = GetCurrentInventoryItems();
    
        foreach (var invItem in inventoryItems)
        {
            var luminaItem = Svc.Data.GetExcelSheet<Item>().FirstOrDefault(i => i.RowId == invItem.BaseItemId);
            if (luminaItem.NotNull(out var t))
                luminaItems.Add(luminaItem);
        }
    
        return luminaItems;
    }

    public static void MapCollectables()
    {
        foreach (var item in Svc.Data.GetExcelSheet<Item>())
        {
            if (item.IsCollectable && item.Name.ExtractText().Contains("Rarefied", StringComparison.OrdinalIgnoreCase))
            {
                PluginLog.Debug($"Maping {item.Name.ExtractText()}");
                PluginLog.Debug(item.ClassJobUse.Value.Name.ExtractText());
            }
        }
    }
public static readonly Dictionary<string, CollectableClasses> RarefiedItemToClassJob = new()
{
    ["1039"] = CollectableClasses.Fisher,
    ["1055"] = CollectableClasses.Fisher,
    ["1078"] = CollectableClasses.Fisher,
    ["1141"] = CollectableClasses.Fisher,
    ["118"] = CollectableClasses.Fisher,
    ["1181"] = CollectableClasses.Fisher,
    ["129"] = CollectableClasses.Fisher,
    ["135"] = CollectableClasses.Fisher,
    ["137"] = CollectableClasses.Fisher,
    ["14"] = CollectableClasses.Fisher,
    ["141"] = CollectableClasses.Fisher,
    ["147"] = CollectableClasses.Fisher,
    ["151"] = CollectableClasses.Fisher,
    ["157"] = CollectableClasses.Fisher,
    ["17"] = CollectableClasses.Fisher,
    ["171"] = CollectableClasses.Fisher,
    ["18"] = CollectableClasses.Fisher,
    ["181"] = CollectableClasses.Fisher,
    ["182"] = CollectableClasses.Fisher,
    ["188"] = CollectableClasses.Fisher,
    ["19"] = CollectableClasses.Fisher,
    ["20"] = CollectableClasses.Fisher,
    ["201"] = CollectableClasses.Fisher,
    ["206"] = CollectableClasses.Fisher,
    ["209"] = CollectableClasses.Fisher,
    ["21"] = CollectableClasses.Fisher,
    ["211"] = CollectableClasses.Fisher,
    ["217"] = CollectableClasses.Fisher,
    ["23"] = CollectableClasses.Fisher,
    ["236"] = CollectableClasses.Fisher,
    ["244"] = CollectableClasses.Fisher,
    ["25"] = CollectableClasses.Fisher,
    ["26"] = CollectableClasses.Fisher,
    ["29"] = CollectableClasses.Fisher,
    ["294"] = CollectableClasses.Fisher,
    ["31"] = CollectableClasses.Fisher,
    ["311"] = CollectableClasses.Fisher,
    ["314"] = CollectableClasses.Fisher,
    ["315"] = CollectableClasses.Fisher,
    ["33"] = CollectableClasses.Fisher,
    ["330"] = CollectableClasses.Fisher,
    ["346"] = CollectableClasses.Fisher,
    ["348"] = CollectableClasses.Fisher,
    ["362"] = CollectableClasses.Fisher,
    ["370"] = CollectableClasses.Fisher,
    ["376"] = CollectableClasses.Fisher,
    ["377"] = CollectableClasses.Fisher,
    ["385"] = CollectableClasses.Fisher,
    ["393"] = CollectableClasses.Fisher,
    ["395"] = CollectableClasses.Fisher,
    ["398"] = CollectableClasses.Fisher,
    ["400"] = CollectableClasses.Fisher,
    ["401"] = CollectableClasses.Fisher,
    ["402"] = CollectableClasses.Fisher,
    ["403"] = CollectableClasses.Fisher,
    ["417"] = CollectableClasses.Fisher,
    ["423"] = CollectableClasses.Fisher,
    ["425"] = CollectableClasses.Fisher,
    ["433"] = CollectableClasses.Fisher,
    ["440"] = CollectableClasses.Fisher,
    ["456"] = CollectableClasses.Fisher,
    ["469"] = CollectableClasses.Fisher,
    ["470"] = CollectableClasses.Fisher,
    ["480"] = CollectableClasses.Fisher,
    ["49"] = CollectableClasses.Fisher,
    ["491"] = CollectableClasses.Fisher,
    ["5"] = CollectableClasses.Fisher,
    ["501"] = CollectableClasses.Fisher,
    ["503"] = CollectableClasses.Fisher,
    ["508"] = CollectableClasses.Fisher,
    ["53"] = CollectableClasses.Fisher,
    ["557"] = CollectableClasses.Fisher,
    ["56"] = CollectableClasses.Fisher,
    ["6"] = CollectableClasses.Fisher,
    ["62"] = CollectableClasses.Fisher,
    ["622"] = CollectableClasses.Fisher,
    ["650"] = CollectableClasses.Fisher,
    ["7"] = CollectableClasses.Fisher,
    ["70"] = CollectableClasses.Fisher,
    ["72"] = CollectableClasses.Fisher,
    ["74"] = CollectableClasses.Fisher,
    ["785"] = CollectableClasses.Fisher,
    ["89"] = CollectableClasses.Fisher,
    ["9"] = CollectableClasses.Fisher,
    ["944"] = CollectableClasses.Fisher,
    ["96"] = CollectableClasses.Fisher,
    ["99"] = CollectableClasses.Fisher,
    ["Rarefied AR-Caean Cotton Boll"] = CollectableClasses.Botanist,
    ["Rarefied AR-Caean Velvet Bottoms"] = CollectableClasses.Weaver,
    ["Rarefied AR-Caean Velvet Work Cap"] = CollectableClasses.Weaver,
    ["Rarefied Abalathian Spring Water"] = CollectableClasses.Miner,
    ["Rarefied Acacia Bark"] = CollectableClasses.Botanist,
    ["Rarefied Acacia Log"] = CollectableClasses.Botanist,
    ["Rarefied Acacia Rod"] = CollectableClasses.Carpenter,
    ["Rarefied Adamantite Bill"] = CollectableClasses.Blacksmith,
    ["Rarefied Adamantite Scutum"] = CollectableClasses.Armorer,
    ["Rarefied Alkahest"] = CollectableClasses.Alchemist,
    ["Rarefied Almasty Serge Gloves"] = CollectableClasses.Weaver,
    ["Rarefied Amber Cloves"] = CollectableClasses.Botanist,
    ["Rarefied Annite"] = CollectableClasses.Miner,
    ["Rarefied Applewood Staff"] = CollectableClasses.Carpenter,
    ["Rarefied Archaeoskin Belt"] = CollectableClasses.Leatherworker,
    ["Rarefied Archaeoskin Cloche"] = CollectableClasses.Leatherworker,
    ["Rarefied Archaeoskin Codex"] = CollectableClasses.Alchemist,
    ["Rarefied Archaeoskin Grimoire"] = CollectableClasses.Alchemist,
    ["Rarefied Archon Loaf"] = CollectableClasses.Culinarian,
    ["Rarefied Artificial Volcanic Rock"] = CollectableClasses.Miner,
    ["Rarefied Ash Soil"] = CollectableClasses.Miner,
    ["Rarefied Atrociraptorskin Cap"] = CollectableClasses.Leatherworker,
    ["Rarefied Aurum Regis Earrings"] = CollectableClasses.Goldsmith,
    ["Rarefied Aurum Regis Sand"] = CollectableClasses.Miner,
    ["Rarefied Baklava"] = CollectableClasses.Culinarian,
    ["Rarefied Banana Ponzecake"] = CollectableClasses.Culinarian,
    ["Rarefied Beech Composite Bow"] = CollectableClasses.Carpenter,
    ["Rarefied Birch Signum"] = CollectableClasses.Carpenter,
    ["Rarefied Bismuth Fat Cat Frypan"] = CollectableClasses.Armorer,
    ["Rarefied Bismuth Ore"] = CollectableClasses.Miner,
    ["Rarefied Bismuth Sledgehammer"] = CollectableClasses.Blacksmith,
    ["Rarefied Black Star Earrings"] = CollectableClasses.Goldsmith,
    ["Rarefied Bloodhemp"] = CollectableClasses.Botanist,
    ["Rarefied Bloodhempen Skirt"] = CollectableClasses.Weaver,
    ["Rarefied Blue Zircon"] = CollectableClasses.Miner,
    ["Rarefied Bluespirit Codex"] = CollectableClasses.Alchemist,
    ["Rarefied Bluespirit Gauntlets"] = CollectableClasses.Armorer,
    ["Rarefied Bluespirit Gunblade"] = CollectableClasses.Blacksmith,
    ["Rarefied Bluespirit Ore"] = CollectableClasses.Miner,
    ["Rarefied Boiled Alpaca Steak"] = CollectableClasses.Culinarian,
    ["Rarefied Book of Aurum Regis"] = CollectableClasses.Alchemist,
    ["Rarefied Br'aaxskin Armlets"] = CollectableClasses.Leatherworker,
    ["Rarefied Br'aaxskin Codex"] = CollectableClasses.Alchemist,
    ["Rarefied Bright Flax"] = CollectableClasses.Botanist,
    ["Rarefied Brightlinen Himation"] = CollectableClasses.Weaver,
    ["Rarefied Cedar Fishing Rod"] = CollectableClasses.Carpenter,
    ["Rarefied Cedar Longbow"] = CollectableClasses.Carpenter,
    ["Rarefied Ceiba Spear"] = CollectableClasses.Carpenter,
    ["Rarefied Chalcocite"] = CollectableClasses.Miner,
    ["Rarefied Chimerical Felt Cyclas"] = CollectableClasses.Weaver,
    ["Rarefied Chirashi-zushi"] = CollectableClasses.Culinarian,
    ["Rarefied Chloroschist"] = CollectableClasses.Miner,
    ["Rarefied Chondrite Alembic"] = CollectableClasses.Armorer,
    ["Rarefied Chondrite Culinary Knife"] = CollectableClasses.Blacksmith,
    ["Rarefied Chondrite Lapidary Hammer"] = CollectableClasses.Blacksmith,
    ["Rarefied Chondrite Needle"] = CollectableClasses.Goldsmith,
    ["Rarefied Chondrite Sollerets"] = CollectableClasses.Armorer,
    ["Rarefied Claro Walnut Fishing Rod"] = CollectableClasses.Carpenter,
    ["Rarefied Claro Walnut Flat Brush"] = CollectableClasses.Alchemist,
    ["Rarefied Claro Walnut Grinding Wheel"] = CollectableClasses.Carpenter,
    ["Rarefied Cobalt Tungsten Chocobo Frypan"] = CollectableClasses.Armorer,
    ["Rarefied Cobalt Tungsten Scimitars"] = CollectableClasses.Blacksmith,
    ["Rarefied Cobalt Tungsten Tuck"] = CollectableClasses.Goldsmith,
    ["Rarefied Coconut"] = CollectableClasses.Botanist,
    ["Rarefied Coral"] = CollectableClasses.Botanist,
    ["Rarefied Crocodileskin Leggings"] = CollectableClasses.Leatherworker,
    ["Rarefied Cunning Craftsman's Tisane"] = CollectableClasses.Alchemist,
    ["Rarefied Dark Chestnut"] = CollectableClasses.Botanist,
    ["Rarefied Dark Chestnut Branch"] = CollectableClasses.Botanist,
    ["Rarefied Dark Chestnut Log"] = CollectableClasses.Botanist,
    ["Rarefied Dark Chestnut Resin"] = CollectableClasses.Botanist,
    ["Rarefied Dark Chestnut Rod"] = CollectableClasses.Carpenter,
    ["Rarefied Dark Chestnut Sap"] = CollectableClasses.Botanist,
    ["Rarefied Dark Mahogany Log"] = CollectableClasses.Botanist,
    ["Rarefied Dark Mahogany Necklace"] = CollectableClasses.Carpenter,
    ["Rarefied Dark Rye"] = CollectableClasses.Botanist,
    ["Rarefied Darkhempen Hat"] = CollectableClasses.Weaver,
    ["Rarefied Deepgold Anelace"] = CollectableClasses.Blacksmith,
    ["Rarefied Deepgold Cuirass"] = CollectableClasses.Armorer,
    ["Rarefied Deepgold Culinary Knife"] = CollectableClasses.Blacksmith,
    ["Rarefied Deepgold Wings"] = CollectableClasses.Armorer,
    ["Rarefied Dhalmel Gratin"] = CollectableClasses.Culinarian,
    ["Rarefied Dhalmelskin Coat"] = CollectableClasses.Leatherworker,
    ["Rarefied Dhalmelskin Codex"] = CollectableClasses.Alchemist,
    ["Rarefied Dissolvent"] = CollectableClasses.Alchemist,
    ["Rarefied Doman Iron Greaves"] = CollectableClasses.Armorer,
    ["Rarefied Doman Iron Uchigatana"] = CollectableClasses.Blacksmith,
    ["Rarefied Doman Steel Patas"] = CollectableClasses.Blacksmith,
    ["Rarefied Doman Steel Tabard"] = CollectableClasses.Armorer,
    ["Rarefied Dragonskin Ring"] = CollectableClasses.Leatherworker,
    ["Rarefied Draught"] = CollectableClasses.Alchemist,
    ["Rarefied Durium Chaplets"] = CollectableClasses.Goldsmith,
    ["Rarefied Durium Rod"] = CollectableClasses.Goldsmith,
    ["Rarefied Dwarven Cotton Beret"] = CollectableClasses.Weaver,
    ["Rarefied Dwarven Mythril Grimoire"] = CollectableClasses.Alchemist,
    ["Rarefied Eblan Alumen"] = CollectableClasses.Miner,
    ["Rarefied Elder Nutmeg"] = CollectableClasses.Botanist,
    ["Rarefied Enchanted Manganese Ink"] = CollectableClasses.Alchemist,
    ["Rarefied Espresso con Panna"] = CollectableClasses.Culinarian,
    ["Rarefied Gaganaskin Shoes"] = CollectableClasses.Leatherworker,
    ["Rarefied Gajaskin Codex"] = CollectableClasses.Alchemist,
    ["Rarefied Gajaskin Shoes"] = CollectableClasses.Leatherworker,
    ["Rarefied Gargantuaskin Hat"] = CollectableClasses.Leatherworker,
    ["Rarefied Gargantuaskin Trousers"] = CollectableClasses.Leatherworker,
    ["Rarefied Gazelleskin Armguards"] = CollectableClasses.Leatherworker,
    ["Rarefied Gazelleskin Codex"] = CollectableClasses.Alchemist,
    ["Rarefied Gemdraught of Vitality"] = CollectableClasses.Alchemist,
    ["Rarefied Gemsap of Dexterity"] = CollectableClasses.Alchemist,
    ["Rarefied Giant Haddock Dip"] = CollectableClasses.Culinarian,
    ["Rarefied Giant Popoto Pancakes"] = CollectableClasses.Culinarian,
    ["Rarefied Ginseng Earrings"] = CollectableClasses.Carpenter,
    ["Rarefied Gliderskin Grimoire"] = CollectableClasses.Alchemist,
    ["Rarefied Gliderskin Thighboots"] = CollectableClasses.Leatherworker,
    ["Rarefied Gomphotherium Brais"] = CollectableClasses.Leatherworker,
    ["Rarefied Grilled Rail"] = CollectableClasses.Culinarian,
    ["Rarefied Growth Formula"] = CollectableClasses.Alchemist,
    ["Rarefied Gyr Abanian Alumen"] = CollectableClasses.Miner,
    ["Rarefied Gyr Abanian Mineral Water"] = CollectableClasses.Miner,
    ["Rarefied Gyuki Leather Jacket"] = CollectableClasses.Leatherworker,
    ["Rarefied Hallowed Chestnut Ring"] = CollectableClasses.Carpenter,
    ["Rarefied Hallowed Ramie Doublet"] = CollectableClasses.Weaver,
    ["Rarefied Happiness Juice"] = CollectableClasses.Culinarian,
    ["Rarefied Hardsilver Monocle"] = CollectableClasses.Goldsmith,
    ["Rarefied Hardsilver Pole"] = CollectableClasses.Goldsmith,
    ["Rarefied High Durium Greatsword"] = CollectableClasses.Blacksmith,
    ["Rarefied High Durium Kite Shield"] = CollectableClasses.Armorer,
    ["Rarefied High Durium Knuckles"] = CollectableClasses.Armorer,
    ["Rarefied High Durium Milpreves"] = CollectableClasses.Goldsmith,
    ["Rarefied High Durium Ore"] = CollectableClasses.Miner,
    ["Rarefied High Durium Pistol"] = CollectableClasses.Blacksmith,
    ["Rarefied High Steel Claw Hammer"] = CollectableClasses.Blacksmith,
    ["Rarefied High Steel Guillotine"] = CollectableClasses.Blacksmith,
    ["Rarefied High Steel Plate Belt"] = CollectableClasses.Armorer,
    ["Rarefied High Steel Thermal Alembic"] = CollectableClasses.Armorer,
    ["Rarefied Holy Cedar Spinning Wheel"] = CollectableClasses.Carpenter,
    ["Rarefied Holy Rainbow Hat"] = CollectableClasses.Weaver,
    ["Rarefied Horse Chestnut Kasa"] = CollectableClasses.Carpenter,
    ["Rarefied Iceberg Lettuce"] = CollectableClasses.Botanist,
    ["Rarefied Ihuykanite Circlet"] = CollectableClasses.Goldsmith,
    ["Rarefied Integral Armillae"] = CollectableClasses.Carpenter,
    ["Rarefied Integral Fishing Rod"] = CollectableClasses.Carpenter,
    ["Rarefied Iridescent Top"] = CollectableClasses.Weaver,
    ["Rarefied Ironwood Grinding Wheel"] = CollectableClasses.Carpenter,
    ["Rarefied Ironwood Log"] = CollectableClasses.Botanist,
    ["Rarefied Kelp"] = CollectableClasses.Botanist,
    ["Rarefied King Crab Cake"] = CollectableClasses.Culinarian,
    ["Rarefied Koppranickel Index"] = CollectableClasses.Alchemist,
    ["Rarefied Koppranickel Necklace"] = CollectableClasses.Goldsmith,
    ["Rarefied Koppranickel Planisphere"] = CollectableClasses.Goldsmith,
    ["Rarefied Kozama'uka Chamomile"] = CollectableClasses.Botanist,
    ["Rarefied Kudzu Hat"] = CollectableClasses.Weaver,
    ["Rarefied Kumbhiraskin Shoes"] = CollectableClasses.Leatherworker,
    ["Rarefied Lar Longbow"] = CollectableClasses.Goldsmith,
    ["Rarefied Larch Log"] = CollectableClasses.Botanist,
    ["Rarefied Larch Necklace"] = CollectableClasses.Carpenter,
    ["Rarefied Larch Sap"] = CollectableClasses.Botanist,
    ["Rarefied Lemonade"] = CollectableClasses.Culinarian,
    ["Rarefied Lignum Vitae Grinding Wheel"] = CollectableClasses.Carpenter,
    ["Rarefied Limonite"] = CollectableClasses.Miner,
    ["Rarefied Loboskin Fingerless Gloves"] = CollectableClasses.Leatherworker,
    ["Rarefied Loboskin Grimoire"] = CollectableClasses.Alchemist,
    ["Rarefied Luncheon Toadskin Grimoire"] = CollectableClasses.Alchemist,
    ["Rarefied Luncheon Toadskin Hose"] = CollectableClasses.Leatherworker,
    ["Rarefied Magnesite Ore"] = CollectableClasses.Miner,
    ["Rarefied Manasilver Ear Cuffs"] = CollectableClasses.Goldsmith,
    ["Rarefied Manasilver Sand"] = CollectableClasses.Miner,
    ["Rarefied Manganese Armor of the Behemoth King"] = CollectableClasses.Armorer,
    ["Rarefied Manganese Cross-pein Hammer"] = CollectableClasses.Blacksmith,
    ["Rarefied Manganese Horn of the Last Unicorn"] = CollectableClasses.Goldsmith,
    ["Rarefied Marid Leather Corset"] = CollectableClasses.Leatherworker,
    ["Rarefied Marron Glace"] = CollectableClasses.Culinarian,
    ["Rarefied Max-Potion"] = CollectableClasses.Alchemist,
    ["Rarefied Miracle Apple Log"] = CollectableClasses.Botanist,
    ["Rarefied Molybdenum Headgear"] = CollectableClasses.Armorer,
    ["Rarefied Molybdenum Pliers"] = CollectableClasses.Blacksmith,
    ["Rarefied Moon Gel"] = CollectableClasses.Alchemist,
    ["Rarefied Mountain Chromite Alembic"] = CollectableClasses.Armorer,
    ["Rarefied Mountain Chromite Fists"] = CollectableClasses.Blacksmith,
    ["Rarefied Mountain Flax"] = CollectableClasses.Botanist,
    ["Rarefied Mountain Linen Top"] = CollectableClasses.Weaver,
    ["Rarefied Mythril Alembic"] = CollectableClasses.Armorer,
    ["Rarefied Mythril Hatchet"] = CollectableClasses.Blacksmith,
    ["Rarefied Mythril Ring"] = CollectableClasses.Goldsmith,
    ["Rarefied Mythrite Bangle"] = CollectableClasses.Goldsmith,
    ["Rarefied Mythrite Bladed Lantern Shield"] = CollectableClasses.Armorer,
    ["Rarefied Mythrite Goggles"] = CollectableClasses.Goldsmith,
    ["Rarefied Mythrite Halfheart Saw"] = CollectableClasses.Blacksmith,
    ["Rarefied Mythrite Hauberk"] = CollectableClasses.Armorer,
    ["Rarefied Mythrite Katzbalger"] = CollectableClasses.Blacksmith,
    ["Rarefied Mythrite Needle"] = CollectableClasses.Goldsmith,
    ["Rarefied Mythrite Pugiones"] = CollectableClasses.Blacksmith,
    ["Rarefied Mythrite Sallet"] = CollectableClasses.Armorer,
    ["Rarefied Mythrite Sand"] = CollectableClasses.Miner,
    ["Rarefied Night Pepper"] = CollectableClasses.Botanist,
    ["Rarefied Ophiotauroskin Halfgloves"] = CollectableClasses.Leatherworker,
    ["Rarefied Ophiotauroskin Magitek Codex"] = CollectableClasses.Alchemist,
    ["Rarefied Ophiotauroskin Top"] = CollectableClasses.Leatherworker,
    ["Rarefied Ovim Wool Tunic"] = CollectableClasses.Weaver,
    ["Rarefied Palladium Needle"] = CollectableClasses.Goldsmith,
    ["Rarefied Palm Bracelet"] = CollectableClasses.Carpenter,
    ["Rarefied Palm Log"] = CollectableClasses.Botanist,
    ["Rarefied Peperoncino"] = CollectableClasses.Culinarian,
    ["Rarefied Persimmon Bracelets"] = CollectableClasses.Carpenter,
    ["Rarefied Persimmon Pudding"] = CollectableClasses.Culinarian,
    ["Rarefied Pewter Choker"] = CollectableClasses.Goldsmith,
    ["Rarefied Pewter Ore"] = CollectableClasses.Miner,
    ["Rarefied Phrygian Earring"] = CollectableClasses.Goldsmith,
    ["Rarefied Phrygian Gold Ore"] = CollectableClasses.Miner,
    ["Rarefied Pine Cane"] = CollectableClasses.Carpenter,
    ["Rarefied Pine Log"] = CollectableClasses.Botanist,
    ["Rarefied Pine Resin"] = CollectableClasses.Botanist,
    ["Rarefied Pixie Apple"] = CollectableClasses.Botanist,
    ["Rarefied Pixie Cotton Hood"] = CollectableClasses.Weaver,
    ["Rarefied Popotoes au Gratin"] = CollectableClasses.Culinarian,
    ["Rarefied Pyrite"] = CollectableClasses.Miner,
    ["Rarefied Ra'Kaznar Greaves"] = CollectableClasses.Armorer,
    ["Rarefied Ra'Kaznar Ore"] = CollectableClasses.Miner,
    ["Rarefied Ra'Kaznar Orrery"] = CollectableClasses.Goldsmith,
    ["Rarefied Ra'Kaznar Ring"] = CollectableClasses.Armorer,
    ["Rarefied Ra'Kaznar Round Knife"] = CollectableClasses.Blacksmith,
    ["Rarefied Ra'Kaznar War Scythe"] = CollectableClasses.Blacksmith,
    ["Rarefied Rainbow Bolero"] = CollectableClasses.Weaver,
    ["Rarefied Rainbow Cotton Boll"] = CollectableClasses.Botanist,
    ["Rarefied Rainbow Ribbon"] = CollectableClasses.Weaver,
    ["Rarefied Ramie Turban"] = CollectableClasses.Weaver,
    ["Rarefied Raw Ametrine"] = CollectableClasses.Miner,
    ["Rarefied Raw Azurite"] = CollectableClasses.Miner,
    ["Rarefied Raw Dark Amber"] = CollectableClasses.Miner,
    ["Rarefied Raw Ihuykanite"] = CollectableClasses.Miner,
    ["Rarefied Raw Kyanite"] = CollectableClasses.Miner,
    ["Rarefied Raw Lazurite"] = CollectableClasses.Miner,
    ["Rarefied Raw Onyx"] = CollectableClasses.Miner,
    ["Rarefied Raw Petalite"] = CollectableClasses.Miner,
    ["Rarefied Raw Star Spinel"] = CollectableClasses.Miner,
    ["Rarefied Raw Triphane"] = CollectableClasses.Miner,
    ["Rarefied Red Pine Log"] = CollectableClasses.Botanist,
    ["Rarefied Red Pine Spinning Wheel"] = CollectableClasses.Carpenter,
    ["Rarefied Reef Rock"] = CollectableClasses.Miner,
    ["Rarefied Reisui"] = CollectableClasses.Alchemist,
    ["Rarefied Royal Eggs"] = CollectableClasses.Culinarian,
    ["Rarefied Rroneek Serge Hat"] = CollectableClasses.Weaver,
    ["Rarefied Ruby Cotton Gilet"] = CollectableClasses.Weaver,
    ["Rarefied Ruthenium Sabatons"] = CollectableClasses.Armorer,
    ["Rarefied Ruthenium War Axe"] = CollectableClasses.Blacksmith,
    ["Rarefied Saigaskin Gloves"] = CollectableClasses.Leatherworker,
    ["Rarefied Salmon Jerky"] = CollectableClasses.Culinarian,
    ["Rarefied Sandteak Fauchard"] = CollectableClasses.Carpenter,
    ["Rarefied Sandteak Log"] = CollectableClasses.Botanist,
    ["Rarefied Sarcenet Kecks"] = CollectableClasses.Weaver,
    ["Rarefied Sauteed Porcini"] = CollectableClasses.Culinarian,
    ["Rarefied Scarlet Moko Wedge Cap"] = CollectableClasses.Weaver,
    ["Rarefied Sea Salt"] = CollectableClasses.Miner,
    ["Rarefied Serge Hose"] = CollectableClasses.Weaver,
    ["Rarefied Serpentskin Hat"] = CollectableClasses.Leatherworker,
    ["Rarefied Sharlayan Rock Salt"] = CollectableClasses.Miner,
    ["Rarefied Shiitake Mushroom"] = CollectableClasses.Botanist,
    ["Rarefied Shorlog"] = CollectableClasses.Culinarian,
    ["Rarefied Silvergrace Ore"] = CollectableClasses.Miner,
    ["Rarefied Smilodonskin Trousers"] = CollectableClasses.Leatherworker,
    ["Rarefied Snow Cotton Beret"] = CollectableClasses.Weaver,
    ["Rarefied Snow Linen Doublet"] = CollectableClasses.Weaver,
    ["Rarefied Sohm Al Tart"] = CollectableClasses.Culinarian,
    ["Rarefied Spaghetti al Nero"] = CollectableClasses.Culinarian,
    ["Rarefied Star Quartz Choker"] = CollectableClasses.Goldsmith,
    ["Rarefied Stonegold Degen"] = CollectableClasses.Goldsmith,
    ["Rarefied Stonegold Orrery"] = CollectableClasses.Goldsmith,
    ["Rarefied Stuffed Peppers"] = CollectableClasses.Culinarian,
    ["Rarefied Swallowskin Coat"] = CollectableClasses.Leatherworker,
    ["Rarefied Sweet Kukuru Bean"] = CollectableClasses.Botanist,
    ["Rarefied Sykon"] = CollectableClasses.Botanist,
    ["Rarefied Sykon Bavarois"] = CollectableClasses.Culinarian,
    ["Rarefied Syrup"] = CollectableClasses.Alchemist,
    ["Rarefied Tacos de Carne Asada"] = CollectableClasses.Culinarian,
    ["Rarefied Tempura Platter"] = CollectableClasses.Culinarian,
    ["Rarefied Thavnairian Perilla Leaf"] = CollectableClasses.Botanist,
    ["Rarefied Thunderyards Silk Culottes"] = CollectableClasses.Weaver,
    ["Rarefied Thunderyards Silk Gloves"] = CollectableClasses.Weaver,
    ["Rarefied Tigerskin Grimoire"] = CollectableClasses.Alchemist,
    ["Rarefied Tigerskin Tricorne"] = CollectableClasses.Leatherworker,
    ["Rarefied Titanbronze Headgear"] = CollectableClasses.Goldsmith,
    ["Rarefied Titanbronze Pickaxe"] = CollectableClasses.Blacksmith,
    ["Rarefied Titanbronze Tower Shield"] = CollectableClasses.Armorer,
    ["Rarefied Titancopper Ore"] = CollectableClasses.Miner,
    ["Rarefied Titanium Creasing Knife"] = CollectableClasses.Blacksmith,
    ["Rarefied Titanium Frypan"] = CollectableClasses.Armorer,
    ["Rarefied Titanium Gold Mortar"] = CollectableClasses.Blacksmith,
    ["Rarefied Titanium Gold Ore"] = CollectableClasses.Miner,
    ["Rarefied Titanium Gold Thorned Corselet"] = CollectableClasses.Armorer,
    ["Rarefied Titanium Mortar"] = CollectableClasses.Blacksmith,
    ["Rarefied Titanium Vambraces"] = CollectableClasses.Armorer,
    ["Rarefied Tungsten Ore"] = CollectableClasses.Miner,
    ["Rarefied Turali Pineapple Ponzecake"] = CollectableClasses.Culinarian,
    ["Rarefied Twinsilk Apron"] = CollectableClasses.Weaver,
    ["Rarefied Urunday Log"] = CollectableClasses.Botanist,
    ["Rarefied White Ash Earrings"] = CollectableClasses.Carpenter,
    ["Rarefied White Gold Choker"] = CollectableClasses.Goldsmith,
    ["Rarefied White Gold Ore"] = CollectableClasses.Miner,
    ["Rarefied White Oak Log"] = CollectableClasses.Botanist,
    ["Rarefied White Oak Partisan"] = CollectableClasses.Carpenter,
    ["Rarefied Wild Agave"] = CollectableClasses.Botanist,
    ["Rarefied Windsbalm Bay Leaf"] = CollectableClasses.Botanist,
    ["Rarefied Wyvernskin Mask"] = CollectableClasses.Leatherworker,
    ["Rarefied Zelkova Spinning Wheel"] = CollectableClasses.Carpenter,
    ["Rarefied Zonureskin Fingerless Gloves"] = CollectableClasses.Leatherworker,
};
}
